apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-api
  template:
    metadata:
      labels:
        app: devops-api
    spec:
      containers:
      - name: api
        image: devops-api:latest
        ports:
        - containerPort: 8000
